services:
  - type: web
    name: my-app
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/my-app-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SERVER_PORT
        value: 8080